# generated by datamodel-codegen:
#   filename:  wide-event.schema.json

from __future__ import annotations

from enum import StrEnum
from typing import Any, Dict, Literal

from pydantic import BaseModel, ConfigDict


class AuthStatus(StrEnum):
    authenticated = 'authenticated'
    anonymous = 'anonymous'


class Environment(StrEnum):
    production = 'production'
    staging = 'staging'
    development = 'development'


class Error(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    code: str | None = None
    message: str | None = None
    type: str


class Outcome(StrEnum):
    success = 'success'
    error = 'error'
    cancelled = 'cancelled'


class Runtime(StrEnum):
    web = 'web'
    react_native = 'react_native'
    convex = 'convex'
    python = 'python'


class WideEvent(BaseModel):
    model_config = ConfigDict(
        extra='allow',
    )
    __annotations__ = {
        '__pydantic_extra__': Dict[str, Any],
    }
    auth_status: AuthStatus | None = None
    deployment: str | None = None
    duration_ms: float
    environment: Environment
    error: Error | None = None
    event: str
    event_id: str
    experiment_key: str | None = None
    experiment_variant: str | None = None
    function_type: str | None = None
    method: str | None = None
    outcome: Outcome
    parent_span_id: str | None = None
    region: str | None = None
    request_id: str | None = None
    route: str | None = None
    runtime: Runtime
    sample_rate: float | None = None
    sampled: bool | None = None
    schema_version: Literal[1]
    sentry_event_id: str | None = None
    service: str | None = None
    service_version: str | None = None
    session_id: str | None = None
    span_id: str
    status_code: float | None = None
    trace_id: str
    ts: str
    user_id_hash: str | None = None
    user_tier: str | None = None
